# Generated by Django 5.1.4 on 2024-12-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
